export const CHECKLIST_DEFAULTS: Record<string, string[]> = {
  HEATING: [
    'Brenner reinigen und prüfen',
    'Wärmetauscher reinigen',
    'Abgaswerte messen',
    'Betriebsdruck prüfen',
    'Ausdehnungsgefäß prüfen',
    'Sicherheitsventil prüfen',
    'Filter reinigen oder wechseln',
    'Dichtheitsprüfung',
    'Regelung und Thermostat prüfen',
    'Warmwasserbereitung prüfen',
  ],
  AC: [
    'Luftfilter reinigen',
    'Kondensator reinigen',
    'Kältemitteldruck prüfen',
    'Kondenswasserablauf prüfen',
    'Elektrische Anschlüsse prüfen',
    'Betriebstemperaturen messen',
    'Fernbedienung und Steuerung prüfen',
  ],
  WATER_TREATMENT: [
    'Salzvorrat prüfen und nachfüllen',
    'Regeneration prüfen',
    'Filterwechsel prüfen',
    'Wasserhärte messen',
    'Druckverlust prüfen',
    'Desinfektion prüfen',
  ],
  ENERGY_STORAGE: [
    'Ladestand prüfen',
    'Batteriespannung messen',
    'Anschlüsse und Kabel prüfen',
    'Batterie-Management-System prüfen',
    'Temperaturen prüfen',
    'Wechselrichter prüfen',
  ],
};
